stages:
  - compile
  - test
  - package
  - docker

variables:
  BACKEND_IMAGE: "hkiriiheb/servify-backend"
  FRONTEND_IMAGE: "hkiriiheb/servify-frontend"
  DOCKER_TLS_CERTDIR: ""

# ======================
# BACKEND - COMPILE
# ======================
backend_compile:
  stage: compile
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml -q -B clean compile

# ======================
# BACKEND - TEST
# ======================
backend_test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  services:
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_DATABASE: servify
    MYSQL_ROOT_PASSWORD: Mysql123@@
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/servify?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: Mysql123@@
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
  script:
    -echo " Waiting for MySQL..."
    -until mysqladmin ping -h mysql -u root -p Mysql123@@ --silent; do sleep 2; done
    - mvn -f backend/pom.xml -q -B test

# ======================
# BACKEND - PACKAGE
# ======================
backend_package:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml -q -B package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

# ======================
# FRONTEND - PACKAGE
# ======================
frontend_package:
  stage: package
  image: node:20
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

# ======================
# BACKEND - DOCKER
# ======================
backend_docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - cp backend/target/*.jar backend/app.jar
    - docker build -t $BACKEND_IMAGE:latest backend
    - docker push $BACKEND_IMAGE:latest
  dependencies:
    - backend_package

# ======================
# FRONTEND - DOCKER
# ======================
frontend_docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $FRONTEND_IMAGE:latest frontend
    - docker push $FRONTEND_IMAGE:latest
  dependencies:
    - frontend_package
