stages:
  - compile
  - test
  - package
  - docker


  

# ======================
# COMPILE
# ======================
compile-job:
  stage: compile
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml -q -B clean compile

# ======================
# TEST
# ======================
test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml -q -B test

# ======================
# PACKAGE
# ======================
package-job:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml -q -B package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

# ======================
# DOCKER
# ======================
docker-job:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: hkiriiheb/servify-backend
  script:
    - cp backend/target/*.jar backend/app.jar
    - docker build -t $IMAGE_NAME:latest backend
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker push $IMAGE_NAME:latest
  dependencies:
    - package-job
