stages:
  - build
  - docker

variables:
  FRONTEND_IMAGE: "hkiriiheb/servify-frontend"
  BACKEND_IMAGE: "hkiriiheb/servify-backend"
  DOCKER_TLS_CERTDIR: ""

# ======================
# FRONTEND BUILD
# ======================
frontend_build:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

# ======================
# BACKEND BUILD
# ======================
backend_build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn -f backend/pom.xml clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

# ======================
# FRONTEND DOCKER
# ======================
frontend_docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u "hkiriiheb" -p "dockerhub123@@"
  script:
    - docker build -t hkiriiheb/servify-frontend:latest frontend
    - docker push hkiriiheb/servify-frontend:latest
  needs:
    - frontend_build

# ======================
# BACKEND DOCKER
# ======================
backend_docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u "hkiriiheb" -p "dockerhub123@@"
  script:
    - docker build -t hkiriiheb/servify-backend:latest backend
    - docker push hkiriiheb/servify-backend:latest
  needs:
    - backend_build
